[project]
name = "coursework"
version = "0.1.0"
description = "Code written for the data analysis report coursework of the CEG8006 module."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geopandas>=1.1.1",
    "pandas>=2.3.3",
    "plotly>=6.3.1",
    "requests>=2.32.5",
]
